import Razorpay from 'razorpay';
import crypto from 'crypto';
import { config } from '../../config/env';

// Initialize Razorpay instance
const razorpay = new Razorpay({
  key_id: config.razorpay.keyId,
  key_secret: config.razorpay.keySecret,
});

/**
 * Create a Razorpay Order ID for a specific amount.
 * Amount should be in INR (we will multiply by 100 inside to convert to paise).
 */
export async function createOrder(amountInINR: number, receiptId: string) {
  const options = {
    amount: Math.round(amountInINR * 100), // Razorpay expects amount in paise (smallest currency unit)
    currency: 'INR',
    receipt: receiptId,
  };

  const order = await razorpay.orders.create(options);
  return order;
}

/**
 * Verify the Razorpay payment signature after successful frontend checkout.
 */
export function verifySignature(orderId: string, paymentId: string, signature: string): boolean {
  // The signature is generated by HMAC SHA256 using the orderId + "|" + paymentId, signed with our Key Secret.
  const body = orderId + '|' + paymentId;
  const expectedSignature = crypto
    .createHmac('sha256', config.razorpay.keySecret)
    .update(body.toString())
    .digest('hex');

  return expectedSignature === signature;
}
